#!/bin/bash
# Use this config to enable the bash completion
# complete -o filenames -F _root_command notify

$* && \
notify-send "Cool~ \"$*\" finished!" -i 'emblem-cool' || \
notify-send "Oh no! \"$*\" failed!" -i 'emblem-ohno'
