#!/bin/bash

for module in `ls`;
do
	if [ -e ${module}/.bzr ] || [ -e ${module}/.svn ] || [ -e ${module}/.git ];then
		echo "Start sync ${module}..."
		pushd $PWD/${module} > /dev/null
			if [ -e .bzr ];then
				echo "bzr pull"
				bzr pull
			elif [ -e .git ];then
				echo "git pull"
				git pull
			elif [ -e .svn ];then
				echo "svn up"
				svn up
			fi
		popd >/dev/null
		echo -e "Finish sync ${module}\n"
	fi
done

echo "All repository has been synced!"
