######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 16 14:15:24 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += file.cpp
