######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 24 14:53:40 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += window.cpp
