######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 16 14:10:42 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qt-demo.cpp
