#!/bin/bash 
function echo_cpu {
	echo $1
	echo $2
}
cpuinfo=`/usr/bin/sar -u 1 3 | grep Average | awk '{print $3, $5}'` 
upinfo=`/usr/bin/uptime | cut -d \, -f 1` 
echo_cpu $cpuinfo
echo $upinfo
hostname 
