#!/bin/sh

set -e

APP=ubuntu-tweak

VERSION=`cd $HOME/Sources/ubuntu-tweak && python -c 'import ubuntutweak;print ubuntutweak.__version__'`

rm -rf ubuntu-tweak*

./batch-build $APP $VERSION lucid maverick natty

./upload
