#!/bin/sh


if [ -n "$1" ];then
	APPLICATION=$1
else
	APPLICATION=ubuntu-tweak
fi

if [ -n "$2" ];then
	VERSION=$2
else
	VERSION=0.4.7
fi

if [ -n "$3" ];then
	DISTRO=$3
else
	DISTRO=hardy
fi

if [ -n "$4" ];then
	MODE=$4
else
	MODE=daily
fi

VERSION=$2
DISTRO=$3
MKLOG=$PWD/mkchangelog

SRC_ROOT=$HOME/Sources/$APPLICATION
BUILD_DIR=$HOME/build
BUILD_ROOT=$BUILD_DIR/$APPLICATION

CLEAN_OLD() {
	rm -rf $BUILD_ROOT
}

CLEAN_OLD

CLEAN_SRC() {
	rm -rf $BUILD_ROOT/.git
	rm -rf $BUILD_ROOT/.gitignore
	cd $BUILD_ROOT
	find -name '*.pyc' | xargs rm 
}

INFO() {
	echo $APPLICATION
	echo $VERSION
	echo $DISTRO
	echo $SRC_ROOT
	echo $BUILD_ROOT
}
INFO

if [ ! -d $BUILD_DIR ];then
	mkdir $BUILD_DIR
fi

cd $SRC_ROOT
#git pull

cp -r $SRC_ROOT $BUILD_ROOT/
cp -r $BUILD_ROOT/deb/$DISTRO $BUILD_ROOT/debian
rm -r $BUILD_ROOT/deb
rm -r $BUILD_ROOT/rpmspec
$MKLOG $APPLICATION $VERSION $DISTRO $BUILD_ROOT/debian/changelog $MODE
CLEAN_SRC

cd $BUILD_ROOT
debuild -S -sa
