#!/usr/bin/python

import sys
import time

TEMPLATE = '''%(app)s (%(major)s~%(minor)s) %(distro)s; urgency=low

%(changelog)s

 -- TualatriX <tualatrix@gmail.com>  %(timestamp)s

'''

def make_changelog_content(changelog):
    list = []
    for line in changelog.split('\n'):
        line = '  * ' + line
        list.append(line)

    return ''.join(list)

def make_timestamp():
    return time.strftime('%a, %d %b %Y %X +0800', time.localtime())

def make_daily_timestamp(distro):
    return '%s~%s1' % (time.strftime('%Y%m%d', time.localtime()), distro)

def make_changelog_section(app, major, minor, distro, changelog):
    global TEMPLATE
    return TEMPLATE % {
                'app': app, 
                'major': major, 
                'minor': minor, 
                'distro': distro, 
                'changelog': make_changelog_content(changelog),
                'timestamp': make_timestamp()
            }

def make_daily(app, version, distro, file):
    data = open(file).read()
    section = make_changelog_section('ubuntu-tweak', version + '-0', make_daily_timestamp(distro), distro, 'daily build')
    f = open(file, 'w')
    f.write(section + data)
    f.close()

if __name__ == '__main__':
#    print make_changelog_section('ubuntu-tweak', '0.4.6-1', 'hardy1', 'hardy', 'fix a bug')
#    print make_daily('ubuntu-tweak', '0.4.7', 'jaunty', 'changelog')
    make_daily(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
