#!/bin/sh


if [ -n "$1" ];then
	APPLICATION=$1
else
	APPLICATION=ubuntu-tweak
fi

if [ -n "$2" ];then
	VERSION=$2
else
	VERSION=0.4.7
fi

if [ -n "$3" ];then
	DISTRO=$3
else
	DISTRO=hardy
fi

VERSION=$2
DISTRO=$3
MKLOG=$PWD/mkchangelog

SRC_ROOT=$HOME/Sources/$APPLICATION
BUILD_ROOT=$HOME/Sources/$APPLICATION/dist
BUILD_DIR=$BUILD_ROOT/$APPLICATION-$VERSION
TARBALL=$BUILD_ROOT/$APPLICATION-$VERSION.tar.gz
ORIGBALL=$BUILD_ROOT/${APPLICATION}_${VERSION}.orig.tar.gz
CHANGELOG=$BUILD_DIR/debian/changelog

CLEAN_OLD() {
	rm -rf $BUILD_DIR
}

CLEAN_OLD

INFO() {
	echo $APPLICATION
	echo $VERSION
	echo $DISTRO
	echo $SRC_ROOT
	echo $BUILD_DIR
}
INFO

cd $SRC_ROOT

if [ ! -e $ORIGBALL ];then
	python setup.py sdist
	mv -v $TARBALL $ORIGBALL
	NO_SOUCE_UPLOAD=1
fi

tar zxf $ORIGBALL -C $BUILD_ROOT/
cp -vr $SRC_ROOT/debian $BUILD_DIR/debian

REPLACE=`head -1 $CHANGELOG | grep $DISTRO`

if [ ! -n "$REPLACE" ]; then
	echo "Replace the maverick with $DISTRO"
	sed -i "1s/natty/$DISTRO/g" $CHANGELOG
fi

cd $BUILD_DIR
if [ -n "$NO_SOUCE_UPLOAD" ];then
	debuild -S -sa
else
	debuild -S -sd
fi
